// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0ecMdgni4JMjvfEUzN-Xbx53NI5H0J2Q',
    appId: '1:401262977331:web:53ce6b84b5ea194e541e46',
    messagingSenderId: '401262977331',
    projectId: 'dailynews-36fb4',
    authDomain: 'dailynews-36fb4.firebaseapp.com',
    storageBucket: 'dailynews-36fb4.firebasestorage.app',
    measurementId: 'G-90DDD2MSYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh86Pq5DUXPasuS_cNXshouVBBLnQVasQ',
    appId: '1:401262977331:android:4d27ca135234f975541e46',
    messagingSenderId: '401262977331',
    projectId: 'dailynews-36fb4',
    storageBucket: 'dailynews-36fb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkeWfyNNuw6zvO0EVPlFpFQbQQU4KcXms',
    appId: '1:401262977331:ios:52c53e593c8f4f13541e46',
    messagingSenderId: '401262977331',
    projectId: 'dailynews-36fb4',
    storageBucket: 'dailynews-36fb4.firebasestorage.app',
    iosBundleId: 'com.example.symmetryShowcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkeWfyNNuw6zvO0EVPlFpFQbQQU4KcXms',
    appId: '1:401262977331:ios:52c53e593c8f4f13541e46',
    messagingSenderId: '401262977331',
    projectId: 'dailynews-36fb4',
    storageBucket: 'dailynews-36fb4.firebasestorage.app',
    iosBundleId: 'com.example.symmetryShowcase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0ecMdgni4JMjvfEUzN-Xbx53NI5H0J2Q',
    appId: '1:401262977331:web:14bf6212b3cfcc63541e46',
    messagingSenderId: '401262977331',
    projectId: 'dailynews-36fb4',
    authDomain: 'dailynews-36fb4.firebaseapp.com',
    storageBucket: 'dailynews-36fb4.firebasestorage.app',
    measurementId: 'G-F1C9JT3NH6',
  );
}
